---
title: "Week13 Final"
author: "Simran Mallik"
date: "5/2/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(kableExtra)
library(ggplot2)
```
```{r}
# 2020
data2020 <- read.csv("2020.csv")
# 2019 
data2019 <- read.csv("2019.csv")
# 2018
data2018 <- read.csv("2018.csv")
# 2017
data2017 <- read.csv("2017.csv")
# 2016
data2016 <- read.csv("2016.csv")

```

# Number of Players in Each Position By Year 

# TOP 10 SCHOOLS PRODUCING PLAYERS BY POSITION BY YEAR

## OF's
```{r}
# 2016
data2016 %>%
  filter(Pos == 'OF') %>%
  group_by(School) %>%
  count(School) %>%
  filter(!(School == '')) %>%
  filter(n >= 2) %>%
  kable(col.names = c("School", "Number of OF's 2016")) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)

# 2017
data2017 %>%
  filter(Pos == 'OF') %>%
  group_by(School) %>%
  count(School) %>%
  filter(!(School == '')) %>%
  filter(n >= 2) %>%
  kable(col.names = c("School", "Number of OF's   2017")) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)

# 2018
data2018 %>%
  filter(Pos == 'OF') %>%
  group_by(School) %>%
  count(School) %>%
  filter(!(School == '')) %>%
  filter(n >= 2) %>%
  kable(col.names = c("School", "Number of OF's 2018")) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)

# 2019
data2019 %>%
  filter(Position == 'OF') %>%
  group_by(School) %>%
  count(School) %>%
  filter(!(School == '')) %>%
  filter(n >= 2) %>%
  kable(col.names = c("School", "Number of OF's 2019")) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)

# 2020
data2020 %>%
  filter(Position == 'OF') %>%
  group_by(School) %>%
  count(School) %>%
  filter(!(School == '')) %>%
  filter(n >= 2) %>%
  kable(col.names = c("School", "Number of OF's 2019")) %>%
  kable_styling(bootstrap_options = "striped", full_width = F) 



```
## 3B
```{r}
# 2016
data2016 %>%
  filter(Pos == '3B') %>%
  group_by(School) %>%
  count(School) %>%
  filter(!(School == '')) %>%
  filter(n >= 2) %>%
  kable(col.names = c("School", "Number of 3B's   2016")) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)

# 2017
data2017 %>%
  filter(Pos == '3B') %>%
  group_by(School) %>%
  count(School) %>%
  filter(!(School == '')) %>%
  filter(n >= 2) %>%
  kable(col.names = c("School", "Number of 3B's   2017")) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)

# 2018
data2018 %>%
  filter(Pos == '3B') %>%
  group_by(School) %>%
  count(School) %>%
  filter(!(School == '')) %>%
  filter(n >= 2) %>%
  kable(col.names = c("School", "Number of 3B's   2018")) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)

# 2019
data2019 %>%
  filter(Position == '3B') %>%
  group_by(School) %>%
  count(School) %>%
  filter(!(School == '')) %>%
  filter(n >= 2) %>%
  kable(col.names = c("School", "Number of 3B's   2019")) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)

# 2020
data2020 %>%
  filter(Position == '3B') %>%
  group_by(School) %>%
  count(School) %>%
  filter(!(School == '')) %>%
  filter(n >= 2) %>%
  kable(col.names = c("School", "Number of 3B's   2020")) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)
```

## RHP
```{r}
# 2016
data2016 %>%
  filter(Pos == 'RHP') %>%
  group_by(School) %>%
  count(School) %>%
  filter(!(School == '')) %>%
  filter(n >= 4) %>%
  kable(col.names = c("School", "Number of RHP's   2016")) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)

# 2017
data2017 %>%
  filter(Pos == 'RHP') %>%
  group_by(School) %>%
  count(School) %>%
  filter(!(School == '')) %>%
  filter(n >= 4) %>%
  kable(col.names = c("School", "Number of RHP's   2017")) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)

# 2018
data2018 %>%
  filter(Pos == 'RHP') %>%
  group_by(School) %>%
  count(School) %>%
  filter(!(School == '')) %>%
  filter(n >= 4) %>%
  kable(col.names = c("School", "Number of RHP's   2018")) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)

# 2019
data2019 %>%
  filter(Position == 'RHP') %>%
  group_by(School) %>%
  count(School) %>%
  filter(!(School == '')) %>%
  filter(n >= 4) %>%
  kable(col.names = c("School", "Number of RHP's   2019")) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)

# 2020
data2020 %>%
  filter(Position == 'RHP') %>%
  group_by(School) %>%
  count(School) %>%
  filter(!(School == '')) %>%
  filter(n >= 4) %>%
  kable(col.names = c("School", "Number of RHP's   2020")) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)
```
## LHP
```{r}
# 2016
data2016 %>%
  filter(Pos == 'LHP') %>%
  group_by(School) %>%
  count(School) %>%
  filter(!(School == '')) %>%
  filter(n >= 3) %>%
  kable(col.names = c("School", "Number of LHP's   2016")) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)

# 2017
data2017 %>%
  filter(Pos == 'LHP') %>%
  group_by(School) %>%
  count(School) %>%
  filter(!(School == '')) %>%
  filter(n >= 3) %>%
  kable(col.names = c("School", "Number of LHP's   2017")) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)

# 2018
data2018 %>%
  filter(Pos == 'LHP') %>%
  group_by(School) %>%
  count(School) %>%
  filter(!(School == '')) %>%
  filter(n >= 3) %>%
  kable(col.names = c("School", "Number of LHP's   2018")) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)

# 2019
data2019 %>%
  filter(Position == 'OF/LHP') %>%
  group_by(School) %>%
  count(School) %>%
  filter(!(School == '')) %>%
  filter(n >= 3) %>%
  kable(col.names = c("School", "Number of LHP's   2019")) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)

# 2020
data2020 %>%
  filter(Position == 'LHP') %>%
  group_by(School) %>%
  count(School) %>%
  filter(!(School == '')) %>%
  filter(n >= 3) %>%
  kable(col.names = c("School", "Number of LHP's   2020")) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)
```
## C
```{r}
# 2016
data2016 %>%
  filter(Pos == 'C') %>%
  group_by(School) %>%
  count(School) %>%
  filter(!(School == '')) %>%
  arrange(desc(n)) %>%
  kable(col.names = c("School", "Number of C's   2016")) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)

# 2017
data2017 %>%
  filter(Pos == 'C') %>%
  group_by(School) %>%
  count(School) %>%
  filter(!(School == '')) %>%
  arrange(desc(n)) %>%
  kable(col.names = c("School", "Number of C's   2017")) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)

# 2018
data2018 %>%
  filter(Pos == 'C') %>%
  group_by(School) %>%
  count(School) %>%
  filter(!(School == '')) %>%
  arrange(desc(n)) %>%
  kable(col.names = c("School", "Number of C's   2018")) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)

# 2019
data2019 %>%
  filter(Position == 'C') %>%
  group_by(School) %>%
  count(School) %>%
  filter(!(School == '')) %>%
  arrange(desc(n)) %>%
  kable(col.names = c("School", "Number of C's   2019")) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)

# 2020
data2020 %>%
  filter(Position == 'C') %>%
  group_by(School) %>%
  count(School) %>%
  filter(!(School == '')) %>%
  arrange(desc(n)) %>%
  kable(col.names = c("School", "Number of C's   2020")) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)
```
## SS
```{r}
# 2016
data2016 %>%
  filter(Pos == 'SS') %>%
  group_by(School) %>%
  count(School) %>%
  filter(!(School == '')) %>%
  filter(n >= 2) %>%
  kable(col.names = c("School", "Number of SS's   2016")) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)

# 2017
data2017 %>%
  filter(Pos == 'SS') %>%
  group_by(School) %>%
  count(School) %>%
  filter(!(School == '')) %>%
  filter(n >= 2) %>%
  kable(col.names = c("School", "Number of SS's   2017")) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)

# 2018
data2018 %>%
  filter(Pos == 'SS') %>%
  group_by(School) %>%
  count(School) %>%
  filter(!(School == '')) %>%
  filter(n >= 2) %>%
  kable(col.names = c("School", "Number of SS's   2018")) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)

# 2019
data2019 %>%
  filter(Position == 'SS') %>%
  group_by(School) %>%
  count(School) %>%
  filter(!(School == '')) %>%
  filter(n >= 2) %>%
  kable(col.names = c("School", "Number of SS's   2019")) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)

# 2020
data2020 %>%
  filter(Position == 'SS') %>%
  group_by(School) %>%
  count(School) %>%
  filter(!(School == '')) %>%
  filter(n >= 2) %>%
  kable(col.names = c("School", "Number of SS's   2020")) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)
```
## 2B
```{r}
# 2016
data2016 %>%
  filter(Pos == '2B') %>%
  group_by(School) %>%
  count(School) %>%
  filter(!(School == '')) %>%
  filter(n >= 2) %>%
  kable(col.names = c("School", "Number of 2B's   2016")) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)

# 2017
data2017 %>%
  filter(Pos == '2B') %>%
  group_by(School) %>%
  count(School) %>%
  filter(!(School == '')) %>%
  filter(n >= 2) %>%
  kable(col.names = c("School", "Number of 2B's   2017")) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)

# 2018
data2018 %>%
  filter(Pos == '2B') %>%
  group_by(School) %>%
  count(School) %>%
  filter(!(School == '')) %>%
  filter(n >= 2) %>%
  kable(col.names = c("School", "Number of 2B's   2018")) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)

# 2019
data2019 %>%
  filter(Position == '2B') %>%
  group_by(School) %>%
  count(School) %>%
  filter(!(School == '')) %>%
  filter(n >= 2) %>%
  kable(col.names = c("School", "Number of 2B's   2019")) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)

# 2020
data2020 %>%
  filter(Position == '2B') %>%
  group_by(School) %>%
  count(School) %>%
  filter(!(School == '')) %>%
  filter(n >= 2) %>%
  kable(col.names = c("School", "Number of 2B's   2020")) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)
```
## 1B
```{r}
# 2016
data2016 %>%
  filter(Pos == '1B') %>%
  group_by(School) %>%
  count(School) %>%
  filter(!(School == '')) %>%
  arrange(desc(n)) %>%
  kable(col.names = c("School", "Number of 1B's   2016")) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)

# 2017
data2017 %>%
  filter(Pos == '1B') %>%
  group_by(School) %>%
  count(School) %>%
  filter(!(School == '')) %>%
  arrange(desc(n)) %>%
  kable(col.names = c("School", "Number of 1B's   2017")) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)

# 2018
data2018 %>%
  filter(Pos == '1B') %>%
  group_by(School) %>%
  count(School) %>%
  filter(!(School == '')) %>%
  arrange(desc(n)) %>%
  kable(col.names = c("School", "Number of 1B's   2018")) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)

# 2019
data2019 %>%
  filter(Position == '1B') %>%
  group_by(School) %>%
  count(School) %>%
  filter(!(School == '')) %>%
  arrange(desc(n)) %>%
  kable(col.names = c("School", "Number of 1B's   2019")) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)

# 2020
data2020 %>%
  filter(Position == '1B') %>%
  group_by(School) %>%
  count(School) %>%
  filter(!(School == '')) %>%
  arrange(desc(n)) %>%
  kable(col.names = c("School", "Number of 1B's   2020")) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)
```
## IF
```{r}
# 2019
head(data2019 %>%
  filter(Position == 'IF') %>%
  group_by(School) %>%
  count(School) %>%
  filter(!(School == '')) %>%
  arrange(desc(n)),10) %>%
  kable(col.names = c("School", "Number of IF's   2019")) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)
```

# TOP 10 STATES PRODUCING PLAYERS BY POSITION EACH YEAR
## OF's
```{r}
# 2016
head(data2016 %>%
  filter(Pos == 'OF') %>%
  group_by(ST) %>%
  count(ST) %>%
  filter(!(ST == '')) %>%
  arrange(desc(n)),10) %>%
  kable(col.names = c("ST", "Number of OF's 2016")) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)

# 2017
head(data2017 %>%
  filter(Pos == 'OF') %>%
  group_by(ST) %>%
  count(ST) %>%
  filter(!(ST == '')) %>%
  arrange(desc(n)),10) %>%
  kable(col.names = c("ST", "Number of OF's    2017")) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)

# 2018
head(data2018 %>%
  filter(Pos == 'OF') %>%
  group_by(ST) %>%
  count(ST) %>%
  filter(!(ST == '')) %>%
  arrange(desc(n)),10) %>%
  kable(col.names = c("ST", "Number of OF's 2018")) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)

# 2019
head(data2019 %>%
  filter(Position == 'OF') %>%
  group_by(ST) %>%
  count(ST) %>%
  filter(!(ST == '')) %>%
  arrange(desc(n)),10) %>%
  kable(col.names = c("ST", "Number of OF's 2019")) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)

# 2020
head(data2020 %>%
  filter(Position == 'OF') %>%
  group_by(ST) %>%
  count(ST) %>%
  filter(!(ST == '')) %>%
  arrange(desc(n)),10) %>%
  kable(col.names = c("ST", "Number of OF's 2020")) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)

```
## 3B
```{r}
# 2016
head(data2016 %>%
  filter(Pos == '3B') %>%
  group_by(ST) %>%
  count(ST) %>%
  filter(!(ST == '')) %>%
  arrange(desc(n)),10) %>%
  kable(col.names = c("ST", "Number of 3B's 2016")) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)

# 2017
head(data2017 %>%
  filter(Pos == '3B') %>%
  group_by(ST) %>%
  count(ST) %>%
  filter(!(ST == '')) %>%
  arrange(desc(n)),10) %>%
  kable(col.names = c("ST", "Number of 3B's 2017")) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)

# 2018
head(data2018 %>%
  filter(Pos == '3B') %>%
  group_by(ST) %>%
  count(ST) %>%
  filter(!(ST == '')) %>%
  arrange(desc(n)),10) %>%
  kable(col.names = c("ST", "Number of 3B's 2018")) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)

# 2019
head(data2019 %>%
  filter(Position == '3B') %>%
  group_by(ST) %>%
  count(ST) %>%
  filter(!(ST == '')) %>%
  arrange(desc(n)),10) %>%
  kable(col.names = c("ST", "Number of 3B's 2019")) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)

# 2020
head(data2020 %>%
  filter(Position == '3B') %>%
  group_by(ST) %>%
  count(ST) %>%
  filter(!(ST == '')) %>%
  arrange(desc(n)),10) %>%
  kable(col.names = c("ST", "Number of 3B's 2020")) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)
```

## RHP
```{r}
# 2016
head(data2016 %>%
  filter(Pos == 'RHP') %>%
  group_by(ST) %>%
  count(ST) %>%
  filter(!(ST == '')) %>%
  arrange(desc(n)),10) %>%
  kable(col.names = c("ST", "Number of RHP's 2016")) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)

# 2017
head(data2017 %>%
  filter(Pos == 'RHP') %>%
  group_by(ST) %>%
  count(ST) %>%
  filter(!(ST == '')) %>%
  arrange(desc(n)),10) %>%
  kable(col.names = c("ST", "Number of RHP's 2017")) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)

# 2018
head(data2018 %>%
  filter(Pos == 'RHP') %>%
  group_by(ST) %>%
  count(ST) %>%
  filter(!(ST == '')) %>%
  arrange(desc(n)),10) %>%
  kable(col.names = c("ST", "Number of RHP's 2018")) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)

# 2019
head(data2019 %>%
  filter(Position == 'RHP') %>%
  group_by(ST) %>%
  count(ST) %>%
  filter(!(ST == '')) %>%
  arrange(desc(n)),10) %>%
  kable(col.names = c("ST", "Number of RHP's 2019")) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)

# 2020
head(data2020 %>%
  filter(Position == 'RHP') %>%
  group_by(ST) %>%
  count(ST) %>%
  filter(!(ST == '')) %>%
  arrange(desc(n)),10) %>%
  kable(col.names = c("ST", "Number of RHP's 2020")) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)
```
## LHP
```{r}
# 2016
head(data2016 %>%
  filter(Pos == 'LHP') %>%
  group_by(ST) %>%
  count(ST) %>%
  filter(!(ST == '')) %>%
  arrange(desc(n)),10) %>%
  kable(col.names = c("ST", "Number of LHP's 2016")) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)

# 2017
head(data2017 %>%
  filter(Pos == 'LHP') %>%
  group_by(ST) %>%
  count(ST) %>%
  filter(!(ST == '')) %>%
  arrange(desc(n)),10) %>%
  kable(col.names = c("ST", "Number of LHP's 2017")) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)

# 2018
head(data2018 %>%
  filter(Pos == 'LHP') %>%
  group_by(ST) %>%
  count(ST) %>%
  filter(!(ST == '')) %>%
  arrange(desc(n)),10) %>%
  kable(col.names = c("ST", "Number of LHP's 2018")) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)

# 2019
head(data2019 %>%
  filter(Position == 'OF/LHP') %>%
  group_by(ST) %>%
  count(ST) %>%
  filter(!(ST == '')) %>%
  arrange(desc(n)),10) %>%
  kable(col.names = c("ST", "Number of LHP's 2019")) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)

# 2020
head(data2020 %>%
  filter(Position == 'LHP') %>%
  group_by(ST) %>%
  count(ST) %>%
  filter(!(ST == '')) %>%
  arrange(desc(n)),10) %>%
  kable(col.names = c("ST", "Number of LHP's 2020")) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)
```
## C
```{r}
# 2016
head(data2016 %>%
  filter(Pos == 'C') %>%
  group_by(ST) %>%
  count(ST) %>%
  filter(!(ST == '')) %>%
  arrange(desc(n)),10) %>%
  kable(col.names = c("ST", "Number of C's 2016")) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)

# 2017
head(data2017 %>%
  filter(Pos == 'C') %>%
  group_by(ST) %>%
  count(ST) %>%
  filter(!(ST == '')) %>%
  arrange(desc(n)),10) %>%
  kable(col.names = c("ST", "Number of C's 2017")) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)

# 2018
head(data2018 %>%
  filter(Pos == 'C') %>%
  group_by(ST) %>%
  count(ST) %>%
  filter(!(ST == '')) %>%
  arrange(desc(n)),10) %>%
  kable(col.names = c("ST", "Number of C's 2018")) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)

# 2019
head(data2019 %>%
  filter(Position == 'C') %>%
  group_by(ST) %>%
  count(ST) %>%
  filter(!(ST == '')) %>%
  arrange(desc(n)),10) %>%
  kable(col.names = c("ST", "Number of C's 2019")) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)

# 2020
head(data2020 %>%
  filter(Position == 'C') %>%
  group_by(ST) %>%
  count(ST) %>%
  filter(!(ST == '')) %>%
  arrange(desc(n)),10) %>%
  kable(col.names = c("ST", "Number of C's 2020")) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)
```
## SS
```{r}
# 2016
head(data2016 %>%
  filter(Pos == 'SS') %>%
  group_by(ST) %>%
  count(ST) %>%
  filter(!(ST == '')) %>%
  arrange(desc(n)),10) %>%
  kable(col.names = c("ST", "Number of SS's 2016")) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)

# 2017
head(data2017 %>%
  filter(Pos == 'SS') %>%
  group_by(ST) %>%
  count(ST) %>%
  filter(!(ST == '')) %>%
  arrange(desc(n)),10) %>%
  kable(col.names = c("ST", "Number of SS's 2017")) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)

# 2018
head(data2018 %>%
  filter(Pos == 'SS') %>%
  group_by(ST) %>%
  count(ST) %>%
  filter(!(ST == '')) %>%
  arrange(desc(n)),10) %>%
  kable(col.names = c("ST", "Number of SS's 2018")) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)

# 2019
head(data2019 %>%
  filter(Position == 'SS') %>%
  group_by(ST) %>%
  count(ST) %>%
  filter(!(ST == '')) %>%
  arrange(desc(n)),10) %>%
  kable(col.names = c("ST", "Number of SS's 2019")) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)

# 2020
head(data2020 %>%
  filter(Position == 'SS') %>%
  group_by(ST) %>%
  count(ST) %>%
  filter(!(ST == '')) %>%
  arrange(desc(n)),10) %>%
  kable(col.names = c("ST", "Number of SS's 2020")) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)
```
## 2B
```{r}
# 2016
head(data2016 %>%
  filter(Pos == '2B') %>%
  group_by(ST) %>%
  count(ST) %>%
  filter(!(ST == '')) %>%
  arrange(desc(n)),10) %>%
  kable(col.names = c("ST", "Number of 2B's  2016")) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)

# 2017
head(data2017 %>%
  filter(Pos == '2B') %>%
  group_by(ST) %>%
  count(ST) %>%
  filter(!(ST == '')) %>%
  arrange(desc(n)),10) %>%
  kable(col.names = c("ST", "Number of 2B's 2017")) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)

# 2018
head(data2018 %>%
  filter(Pos == '2B') %>%
  group_by(ST) %>%
  count(ST) %>%
  filter(!(ST == '')) %>%
  arrange(desc(n)),10) %>%
  kable(col.names = c("ST", "Number of 2B's 2018")) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)

# 2019
head(data2019 %>%
  filter(Position == '2B') %>%
  group_by(ST) %>%
  count(ST) %>%
  filter(!(ST == '')) %>%
  arrange(desc(n)),10) %>%
  kable(col.names = c("ST", "Number of 2B's 2019")) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)

# 2020
head(data2020 %>%
  filter(Position == '2B') %>%
  group_by(ST) %>%
  count(ST) %>%
  filter(!(ST == '')) %>%
  arrange(desc(n)),10) %>%
  kable(col.names = c("ST", "Number of 2B's 2020")) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)
```
## 1B
```{r}
# 2016
head(data2016 %>%
  filter(Pos == '1B') %>%
  group_by(ST) %>%
  count(ST) %>%
  filter(!(ST == '')) %>%
  arrange(desc(n)),10) %>%
  kable(col.names = c("ST", "Number of 1B's 2016")) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)

# 2017
head(data2017 %>%
  filter(Pos == '1B') %>%
  group_by(ST) %>%
  count(ST) %>%
  filter(!(ST == '')) %>%
  arrange(desc(n)),10) %>%
  kable(col.names = c("ST", "Number of 1B's 2017")) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)

# 2018
head(data2018 %>%
  filter(Pos == '1B') %>%
  group_by(ST) %>%
  count(ST) %>%
  filter(!(ST == '')) %>%
  arrange(desc(n)),10) %>%
  kable(col.names = c("ST", "Number of 1B's 2018")) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)

# 2019
head(data2019 %>%
  filter(Position == '1B') %>%
  group_by(ST) %>%
  count(ST) %>%
  filter(!(ST == '')) %>%
  arrange(desc(n)),10) %>%
  kable(col.names = c("ST", "Number of 1B's 2019")) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)

# 2020
head(data2020 %>%
  filter(Position == '1B') %>%
  group_by(ST) %>%
  count(ST) %>%
  filter(!(ST == '')) %>%
  arrange(desc(n)),10) %>%
  kable(col.names = c("ST", "Number of 1B's 2020")) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)
```
## IF
```{r}
# 2019
head(data2019 %>%
  filter(Position == 'IF') %>%
  group_by(State) %>%
  count(State) %>%
  filter(!(State == '')) %>%
  arrange(desc(n)),10) %>%
  kable(col.names = c("State", "Number of IF's 2019")) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)
```
