---
title: "Week5 Project P2"
author: "Simran Mallik"
date: "3/13/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(plotly)
```

# Creating Datasets
```{r}

c <- read.csv("Week 5 Project - dataset c.csv")


csubset <- c[sample(nrow(c),15),]
csubset

# write.xlsx(csubset, "csubset.xlsx")
```

```{r}
a <- read.csv("Week 5 Project - dataset a.csv")

asubset <- a[sample(nrow(a),15),]
asubset
```
```{r}
e <- read.csv("Week 5 Project - dataset e.csv")
set.seed(1)
(esubset <- e[sample(nrow(e),15),])
# write.xlsx(esubset, "esubset.xlsx")
```

# Finalized datasets 
```{r}
(a <- read.csv("dataset_a.csv"))
(b <- read.csv("dataset_b.csv"))
(c <- read.csv("dataset_c.csv"))
(d <- read.csv("dataset_d.csv"))
```
Question:
Is there a statistically significant correlation between the post All-Star break and pre All-Star break averages for each metric?

Correlation tests for each metric in post All-Star Break 2018 and pre All-Star Break 2019: 
```{r}
(data_a_b <- inner_join(a, b, by = "Name"))

# XBH 
cor.test(data_a_b$XBH.x, data_a_b$XBH.y)
ggplotly(ggplot(data_a_b, aes(x = XBH.x, y = XBH.y)) + geom_point(color = 'blue') + labs(title="XBH Pre-All-Star Break 2019 vs XBH Post-All-Star Break 2018", x = "XBH Post-All-Star Break 2018", y = "XBH Pre-All-Star Break 2019") +theme_minimal() + theme(plot.title = element_text(hjust = 0.5)))


# BABIP
cor.test(data_a_b$BABIP.league.average.babip.x,data_a_b$BABIP.league.average.babip.y)
ggplotly(ggplot(data_a_b, aes(x = BABIP.league.average.babip.x, y = BABIP.league.average.babip.y)) + geom_point(color = 'blue') + labs(title="BABIP Pre-All-Star Break 2019 vs BABIP Post-All-Star Break 2018", x = "XBH Post-All-Star Break 2018", y = "BABIP Pre-All-Star Break 2019") +theme_minimal() + theme(plot.title = element_text(hjust = 0.5)))


# BB/K
cor.test(data_a_b$BB.K.x, data_a_b$BB.K.y)
ggplotly(ggplot(data_a_b, aes(x = BB.K.x, y = BB.K.y)) + geom_point(color = 'blue') + labs(title="BB/K Pre-All-Star Break 2019 vs BB/K Post-All-Star Break 2018", x = "BB/K Post-All-Star Break 2018", y = "BB/K Pre-All-Star Break 2019") +theme_minimal() + theme(plot.title = element_text(hjust = 0.5)))

# SO%
cor.test(data_a_b$SO..x,data_a_b$SO..y)
ggplotly(ggplot(data_a_b, aes(x = SO..x, y = SO..y)) + geom_point(color = 'blue') + labs(title="SO% Pre-All-Star Break 2019 vs SO% Post-All-Star Break 2018", x = "SO% Post-All-Star Break 2018", y = "SO% Pre-All-Star Break 2019") +theme_minimal() + theme(plot.title = element_text(hjust = 0.5)))

```
Correlation tests for each metric in post All-Star Break 2019 and first 30 games of 2020: 
```{r}
(data_c_d <- inner_join(c, d, by = "Name"))

# XBH
cor.test(data_c_d$XBH.x, data_c_d$XBH.y)
ggplotly(ggplot(data_a_b, aes(x = XBH.x, y = XBH.y)) + geom_point(color = 'blue') + labs(title="XBH Pre-All-Star Break 2019 vs XBH Post-All-Star Break 2018", x = "XBH Post-All-Star Break 2018", y = "XBH Pre-All-Star Break 2019") +theme_minimal() + theme(plot.title = element_text(hjust = 0.5)))

# BABIP
cor.test(data_c_d$BABIP.league.average.babip.x,data_c_d$BABIP.league.average.babip.y)
ggplotly(ggplot(data_a_b, aes(x = BABIP.league.average.babip.x, y = BABIP.league.average.babip.y)) + geom_point(color = 'blue') + labs(title="BABIP Pre-All-Star Break 2019 vs BABIP Post-All-Star Break 2018", x = "BABIP Post-All-Star Break 2018", y = "BABIP Pre-All-Star Break 2019") +theme_minimal() + theme(plot.title = element_text(hjust = 0.5)))

# BB/K
cor.test(data_c_d$BB.K.x, data_c_d$BB.K.y)
ggplotly(ggplot(data_a_b, aes(x = BB.K.x, y = BB.K.y)) + geom_point(color = 'blue') + labs(title="BB/K Pre-All-Star Break 2019 vs BB/K Post-All-Star Break 2018", x = "BB/K Post-All-Star Break 2018", y = "BB/K Pre-All-Star Break 2019") +theme_minimal() + theme(plot.title = element_text(hjust = 0.5)))

# SO%
cor.test(data_c_d$SO..x,data_c_d$SO..y)
ggplotly(ggplot(data_a_b, aes(x = SO..x, y = SO..y)) + geom_point(color = 'blue') + labs(title="SO% Pre-All-Star Break 2019 vs SO% Post-All-Star Break 2018", x = "SO% Post-All-Star Break 2018", y = "SO% Pre-All-Star Break 2019") +theme_minimal() + theme(plot.title = element_text(hjust = 0.5)))

```

